name: Deploy via SFTP with lftp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy files via SFTP using lftp
        env:
          FTP_HOST: ${{ secrets.SFTP_HOST }}
          FTP_USER: ${{ secrets.SFTP_USERNAME }}
          FTP_PASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          lftp -u $FTP_USER,$FTP_PASS sftp://$FTP_HOST -e "
            set sftp:auto-confirm yes
            mirror -R ./ view-iptv.stream/
            bye
          "
